//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaiThi
    {
        public int IdBaiThi { get; set; }
        public Nullable<int> MaDethi { get; set; }
        public Nullable<int> MaHocsinh { get; set; }
        public Nullable<int> TongDiem { get; set; }
    
        public virtual DeThi DeThi { get; set; }
        public virtual HocSinh HocSinh { get; set; }
    }
}
