//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CauHois
    {
        public CauHois()
        {
            this.NganHangCauHois = new HashSet<NganHangCauHoi>();
        }
    
        public int IdCauHoi { get; set; }
        public string TittleQuestion { get; set; }
        public string Answer { get; set; }
        public string A { get; set; }
        public string B { get; set; }
        public string C { get; set; }
        public string D { get; set; }
        public Nullable<int> MaMonHoc { get; set; }
        public Nullable<int> MaGV { get; set; }
    
        public virtual ICollection<NganHangCauHoi> NganHangCauHois { get; set; }
    }
}
