//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiaoVien
    {
        public GiaoVien()
        {
            this.LopHocs = new HashSet<LopHoc>();
            this.MonHocs = new HashSet<MonHoc>();
        }
    
        public int IdGiaoVien { get; set; }
        public string TenGiaoVien { get; set; }
        public string Usernam { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<LopHoc> LopHocs { get; set; }
        public virtual ICollection<MonHoc> MonHocs { get; set; }
    }
}
