//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocSinh
    {
        public HocSinh()
        {
            this.BaiThis = new HashSet<BaiThi>();
            this.LopHocs = new HashSet<LopHoc>();
        }
    
        public int IdHocSinh { get; set; }
        public string TenHocsinh { get; set; }
        public Nullable<int> MaLop { get; set; }
        public string username { get; set; }
        public string Password { get; set; }
    
        public virtual ICollection<BaiThi> BaiThis { get; set; }
        public virtual ICollection<LopHoc> LopHocs { get; set; }
    }
}
