//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TracNghiemEntities : DbContext
    {
        public TracNghiemEntities()
            : base("name=TracNghiemEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<BaiThi> BaiThis { get; set; }
        public DbSet<CauHois> CauHois { get; set; }
        public DbSet<DeThi> DeThis { get; set; }
        public DbSet<GiaoVien> GiaoViens { get; set; }
        public DbSet<HocSinh> HocSinhs { get; set; }
        public DbSet<LopHoc> LopHocs { get; set; }
        public DbSet<MonHoc> MonHocs { get; set; }
        public DbSet<NganHangCauHoi> NganHangCauHois { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
    }
}
