//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TracNghiem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NganHangCauHoi
    {
        public NganHangCauHoi()
        {
            this.DeThis = new HashSet<DeThi>();
        }
    
        public int IdNganHang { get; set; }
        public Nullable<int> MaCauHoi { get; set; }
    
        public virtual CauHois CauHois { get; set; }
        public virtual ICollection<DeThi> DeThis { get; set; }
    }
}
